name: Tailscale Linux Test

on:
  workflow_dispatch:

jobs:
  tailscale:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          sudo tailscale up \
            --authkey=$TAILSCALE_AUTH_KEY \
            --hostname gh-linux-test \
            --advertise-exit-node

      - name: Check status
        run: |
          tailscale status
          tailscale netcheck

      - name: Setup SSH
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          sudo apt update
          sudo apt install openssh-server -y

          sudo systemctl enable ssh
          sudo systemctl start ssh

          sudo useradd -m -s /bin/bash runner || true
          echo "runner:$RDP_PASSWORD" | sudo chpasswd

          sudo usermod -aG sudo runner

      - name: Check SSH
        run: |
          systemctl status ssh
          ip addr
          tailscale ip -4

      - name: Keep alive
        run: |
          while true; do
            echo "Running..."
            tailscale status
            sleep 60
          done